name: Build Using System LLVM
on:
  pull_request:
  schedule:
    - cron:  '0 16 * * 0'

jobs:
  build-on-linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get -y install curl zlib1g-dev libzstd-dev libncurses-dev
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 19
          sudo apt-get -y install libllvm19 llvm-19 llvm-19-dev llvm-19-runtime clang-19 clang-tools-19 libclang-common-19-dev libclang-19-dev libclang1-19 libomp-19-dev libmlir-19-dev
      - run: |
          cd oclint-scripts
          ./build -no-ninja -llvm-root=/usr/lib/llvm-19
          ./bundle -archive -llvm-root=/usr/lib/llvm-19
  build-on-mac:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          brew update
          brew install llvm@19
      - run: |
          cd oclint-scripts
          ./build -no-ninja -llvm-root=/opt/homebrew/opt/llvm\@19
          ./bundle -archive -llvm-root=/opt/homebrew/opt/llvm\@19
